### ISSUE TITLE
Minecraft 1.13 support

### ISSUE THREAD

**Issue by PyvesB** [PyvesB/AdvancedAchievements#398]
The first Spigot preview of Minecraft 1.13 is now available (see [announcement](https://www.spigotmc.org/threads/bukkit-craftbukkit-spigot-bungeecord-1-13-pre7-development-builds.328883/)).

There has been quite a big overhaul of the API, but hopefully we can guarantee compatibility all the way from Minecraft 1.7.9 to 1.13 without having to drop any versions or develop separate plugin builds.

Please give me a sign if you're interested in helping or testing! :wink:

**Comment by TAfirehawk** [comment]
I would like to help if I can and certainly test.

**Comment by supertassu** [comment]
Hi

**Comment by TAfirehawk** [comment]
Here is the "Block Additions" list tested for launching fireworks in Creative:
Blue Ice			yes
Button			yes, all 7 while holding shift key
Pressure Plate		yes, all 9
Trapdoor			yes, all 7 while holding shift key, except iron doesn't need shift, also all 7 while open
Carved Pumpkin	yes
Conduit			yes, in water
Coral			yes, all 5, in water
Coral Block		yes, all 5, in water
Coral Fan			yes, all 5, in water
Dead Coral Block	yes, all 5
Dead Coral Fan	yes, all 5
Dried Kelp Block	yes
Kelp				yes, in water
Prismarine Stair	yes, all 3
Prismarine Slab	yes, all 3
Seagrass			yes, in water
Sea Pickle		yes
Shulker Box		yes, all 17 while holding shift key
Stripped Bark		yes, all 6
Stripped Log		yes, all 6
Turtle Egg		yes

**Comment by PyvesB** [comment]
@TAfirehawk thanks, that's helpful! I'll finish off fixing the compiler errors with the current implementation, and I'll then use that information to improve things.

@supertassu a lot of Material names have changed, therefore we can't really make a single _gui.yml_ that works well with 1.13 and pre-1.13 versions.
* for existing users with old GUI files, we could probably still guarantee support by relying on legacy Material names (there's a new method `getMaterial(String name, boolean legacyName) ` which allows this).
* for new users generating brand new GUI files, it would be ideal to have a _gui.yml_ that natively targets the old API for pre-1.13 and the new API for 1.13+. We could package a mostly empty _gui.yml_ within the _jar_ file, and populate it dynamically depending on the Minecraft version. We would simply have to extend `updateOldGUI` in the _FileUpdater_ class by adding a version check and back-filling all missing parameters.

What do you think? Would you like to help with this?

**Comment by TAfirehawk** [comment]
I have done a fair share of game modding, Civilization IV mostly, and programming over the years but nothing in java...so I offer my help if I can be of any real help ;) 

I am hoping Spigot updates BuildTools for 1.13 as I haven't played around to get the update manually so I only have a vanilla 1.13 server and client to go along with my Spigot 1.12.2 server with EssentialsX and AACH.

**Comment by PyvesB** [comment]
I barely ever touched Civilization IV, but I am somewhat familiar with Civilization I and II and was a big fan of Civilization III and V, I've still got them installed somewhere. My laptop is probably way too weak to power Civilization VI though. Good times! 😃 

I'm guessing Civilization IV mods were coded in C++? If that's the case, it shouldn't be too hard to pick up Java if you are so inclined.

We've tried improving the _config.yml_ parsing recently (for instance in #395), I can foresee some users having trouble upgrading their configuration as many entity names and material names have changed. One idea could be to extend the parser and make it check whether the sub-categories used in the _Places_, _Breaks_, _Kills_, _Crafts_ and _Breeding_ categories are valid. 

If you (or others) prefer staying on the testing side, I've attached the first plugin version that I have managed to fully build against the 1.13 API. It does not yet handle any of the aquatic plant fertilising you pointed out above and the default configuration files are probably going to cause problems in particular with _/aach list_, but I'm already happy to have ironed out the numerous compilation errors. 👍 

[AdvancedAchievements.zip](https://github.com/PyvesB/AdvancedAchievements/files/2207344/AdvancedAchievements.zip)

**Comment by TAfirehawk** [comment]
Added Pull Request for the updated gui.yml that is updated to 1.13 names as well as sorted the list the same as it appears in /aach list.

**Comment by TAfirehawk** [comment]
Here is the config.yml although I didn't get to test all the achievements since I am playing in survival.

[config.zip](https://github.com/PyvesB/AdvancedAchievements/files/2208108/config.zip)

**Comment by PyvesB** [comment]
Thanks for this! Nevertheless, we should ideally keep _config.yml_ fully compatible with older Minecraft versions, typically `red_sand` will not work on anything below 1.13. For _gui.yml_ it won't be a problem though; as mentioned above it will be fairly easy to generate the file automatically depending on the Minecraft version. 😉

**Comment by TAfirehawk** [comment]
Some of the config.yml fixes are universal and it will need to be like the gui.yml as sand:1 won't work for red_sand in 1.13

I also found using "legacy" names doesn't work in the gui.yml.  I don't know if this problem is in Spigot or AACH.

I added a fork for my edits and 2 pull requests so it should be easier....I hope....

**Comment by PyvesB** [comment]
I think we should drop red sand and change the achievement examples by choosing a Material name that has never changed between version 1.7.9 and 1.13. "red_sandstone" is an example, but maybe we can come up with a better achievement idea! ^^

I have attached a plugin version that should now work with legacy Material names in the GUI (commit 6528b1daa01622ca9e5eb5d50c7ce75ed8b5bfd2). Such backwards compatibility also works for reward items, but not for anything else.

[AdvancedAchievements.zip](https://github.com/PyvesB/AdvancedAchievements/files/2211741/AdvancedAchievements.zip)

To actually submit a pull request, you have to switch to your branch in the GitHub UI and press the pull request button that should appear somewhere above the last commit message. It doesn't matter if it's still work in progress, you can modify it after it has been submitted. 👍

**Comment by TAfirehawk** [comment]
I tried a pull request and hopefully it works.

I am updating to Spigot 1647 and the latest AACH file for testing today.

The "legacy" material names are interesting....how will old Minecraft versions use them so we can have just one config.yml?  There are lots of ways to update config.yml to non-changed materials but aren't the really old Minecraft versions using ItemID numbers?

**Comment by PyvesB** [comment]
The plugin only supports Minecraft versions from 1.7.9 onwards. Therefore using Material names is fine so as long as we pick names that haven't changed over the years. This is basically what the class looked like in 1.7.9: [Material.java](https://github.com/Bukkit/Bukkit/blob/master/src/main/java/org/bukkit/Material.java). 

I've left a few _config.yml_ ideas on the pull request, feel free to come up with some better ones. 😉

**Comment by TAfirehawk** [comment]
Thanks, I saved that list so I can compare.

Yes those are great ideas and I gave my feedback in the pull request....easier than in this thread :)

**Comment by TAfirehawk** [comment]
Something isn't working right in the combo of breaks.  I changed the sand|red_sand to ice|snow and it only counts the ice.  I even changed it to ice|dirt and it still only counted the ice.  Even changing it to dirt|ice still just counted the ice.

**Comment by PyvesB** [comment]
That's odd, I'll look into this issue that only seems to occur with Minecraft 1.13. Right now my computer completely crashes when I launch the game, so I'm trying to reinstall things. I'm a bit bemused, I've never had any problem with my Minecraft setup which is now 5 years old.

**Comment by PyvesB** [comment]
I have improved 1.13 support for the _Fireworks_ and _Fertilising_ achievement categories. Anyone reading this message, please feel free to try it out and see whether there are any achievement count issues, for instance when launching fireworks on some particular blocks/whilst sneaking, when using bone meal underwater, etc.

[AdvancedAchievements.zip](https://github.com/PyvesB/AdvancedAchievements/files/2216130/AdvancedAchievements.zip)

@aurel85 pinging you as well as you had spotted some subtle bugs with some of these categories in the past. 😉

**Comment by TAfirehawk** [comment]
I have been playing on Spigot 1654 and latest AACH with just the previously mentioned issue that doing combo break of sand:dirt it doesn't register the dirt breaks.

**Comment by TAfirehawk** [comment]
Well the first dev build of 1.13 Spigot is out now.....yay!!!

**Comment by aurel85** [comment]
Hi,

I tested with spigot-1.13-R0.1-SNAPSHOT-b1726 and the plugin version above and here is what I noticed :

- The achievement _Fertilising_ does not work at all (no error in the console)
- When I do /aa book there is no more animation and in the console I have this message : _22.07 19:52:35 [Server] WARN Failed to display additional particle effects for books._
- There is no more green or red color for the validated successes or not. I do not know if it's a change or an error : https://sandbox.fr/images/uploads/original/1532284543.png

Well, I did not test everything thoroughly but here is a first return ;)

**Comment by TAfirehawk** [comment]
@aurel85, item #3, those terracotta colors are working for progress at least on my 3 games of testing.  Something else must be wrong....are the rest of the graphics updated on the main /aach list screen?
![capture](https://user-images.githubusercontent.com/40474729/43049480-87158ff4-8dc6-11e8-8339-a804f28d2507.JPG)

**Comment by aurel85** [comment]
Ok I know why I have it, in the gui.yml it remained in the ID 1.12 so with a reset of this file or a modification I guess it will be fixed.

_AchievementNotStarted:
  Item: stained_clay
  Metadata: 14
AchievementStarted:
  Item: stained_clay
  Metadata: 4
AchievementReceived:
  Item: stained_clay
  Metadata: 5_

And yes I have a custom config.

**Comment by PyvesB** [comment]
As far as _gui.yml_ is concerned, I've provided minimal backwards compatibility so that existing files won't blow up when upgrading the plugin. Nevertheless, some old items may map to the same new ones, anf you have to manually update in those cases.

I'll look into the other issues. 😉

**Comment by TAfirehawk** [comment]
Actually the fertilizing was working under water in the next to last version....just got around to testing it.

**Comment by PyvesB** [comment]
@TAfirehawk I had compiled the wrong branch, sorry about that. Her's the proper one:

[AdvancedAchievements.jar.zip](https://github.com/PyvesB/AdvancedAchievements/files/2218139/AdvancedAchievements.jar.zip)

**Comment by aurel85** [comment]
It works half, most of the time when I used my hoe on a block of grass it was not counted, however when I use it on a high grass it counts me well even by doing it several times on the same high grass.

**Comment by TAfirehawk** [comment]
The hoe plowings for me counted 1 out of 8 that ingame statistics shows (tried on dirt and grass block).  I couldn't get it to work on the grass on top of the block, not sure how you are doing that one @aurel85 

@PyvesB that file works much better :)

**Comment by TAfirehawk** [comment]
The bone meal/fertilizing is working too good now.  I used bone meal 6 times and it shows 9 in AACH.

**Comment by PyvesB** [comment]
Thanks for your help! Here's a new version that should address the broken particle effects as well as some of the issues you spotted with the Fertilising and Plowing categories. 😉 

[AdvancedAchievements.jar.zip](https://github.com/PyvesB/AdvancedAchievements/files/2220636/AdvancedAchievements.jar.zip)

**Comment by TAfirehawk** [comment]
Hoe plowing and fertilizing are working now, great job!!

Breaking ice|snow still doesn't register the snow and I left everything default in the yml files.

**Comment by PyvesB** [comment]
@TAfirehawk yes, that's only fixed on the master branch at the moment, which is ahead of the minecraft-1.13 branch. It wasn't a bug exclusive to Minecraft 1.13, so I didn't want to commit it here.

You can use either /aach or /aa for any of the commands, they're aliases. ^^

@aurel85 did you happen to reload you server in the meantime?

**Comment by aurel85** [comment]
@PyvesB With a reboot it's back normally.

**Comment by PyvesB** [comment]
Fish fixed:
[AdvancedAchievements.jar.zip](https://github.com/PyvesB/AdvancedAchievements/files/2220934/AdvancedAchievements.jar.zip)

**Comment by TAfirehawk** [comment]
Confirmed fishing fixed....at least with cod :)

**Comment by PyvesB** [comment]
Salmon is much harder to catch if I recall correctly!

**Comment by TAfirehawk** [comment]
@aurel85 I believe that is the fix in the master and not in 1.13 for combining different materials.

@PyvesB I started adding other plugins to my setup so maybe this isn't 100% AACH but the diamond reward for killing a zombie has a blank name instead of the default diamond name.
![capture](https://user-images.githubusercontent.com/40474729/43146400-2a4d0f26-8f2f-11e8-9567-96ed6ce14d00.JPG)
![capture2](https://user-images.githubusercontent.com/40474729/43146406-2d902100-8f2f-11e8-8d51-79850922f0d4.JPG)
But it does combine in the crafting table so it looks like something wrong with the custom item naming.

**Comment by PyvesB** [comment]
@TAfirehawk that's very odd, I'm not actually able to reproduce this issue. Are you using the default configuration from the version above?

**Comment by TAfirehawk** [comment]
Yes it is default but I have been adding a lot of other plugins.  I just compiled a new Spigot so I will try to reproduce on a fresh install as it might be some conflict with another plugin.

**Comment by TAfirehawk** [comment]
Ok, SpigotMC build 1685 with latest AACH zip file and nothing else installed.
![image](https://user-images.githubusercontent.com/40474729/43223021-bff280d8-901f-11e8-8a14-6379177b7cd5.png)
and
![image](https://user-images.githubusercontent.com/40474729/43223043-d7b6ff46-901f-11e8-9aa7-1f7328676e00.png)
and
![image](https://user-images.githubusercontent.com/40474729/43223058-e8563d8a-901f-11e8-8b39-4d1b839eed18.png)

**Comment by PyvesB** [comment]
Yes, I manage to reproduce it now. It's actually not a bug related to Minecraft 1.13, so I'll fix it directly on _master_. Well spotted!

Overall I'm happy with Minecraft 1.13 support. There may still be a few minor defects here and there, but I think we're almost good to go. I'll leave this issue opened for another day, and merge back into _master_ if nothing major comes up in the meantime. Let's aim for a 5.9.0 release Friday evening. 😉

**Comment by TAfirehawk** [comment]
I agree that it is ready for 1.13 and any leftover issues can be handled with a 5.9.1

**Comment by TAfirehawk** [comment]
I am not sure if this is AACH or CoreProtect but I am starting to add other important 1.13 plugins to my test server to check compatibility.
`[08:59:39 ERROR]: Could not pass event InventoryClickEvent to CoreProtect v2.15.0
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.13.jar:git-Spigot-f68f5a8-e70d864]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.jar:git-Spigot-f68f5a8-e70d864]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.jar:git-Spigot-f68f5a8-e70d864]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.jar:git-Spigot-f68f5a8-e70d864]
        at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:2130) ~[spigot-1.13.jar:git-Spigot-f68f5a8-e70d864]
        at net.minecraft.server.v1_13_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[spigot-1.13.jar:git-Spigot-f68f5a8-e70d864]
        at net.minecraft.server.v1_13_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[spigot-1.13.jar:git-Spigot-f68f5a8-e70d864]
        at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.jar:git-Spigot-f68f5a8-e70d864]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
        at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [spigot-1.13.jar:git-Spigot-f68f5a8-e70d864]
        at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884) [spigot-1.13.jar:git-Spigot-f68f5a8-e70d864]
        at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot-1.13.jar:git-Spigot-f68f5a8-e70d864]
        at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot-1.13.jar:git-Spigot-f68f5a8-e70d864]
        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot-1.13.jar:git-Spigot-f68f5a8-e70d864]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.NullPointerException
        at net.coreprotect.listener.PlayerListener.onInventoryInteract(PlayerListener.java:77) ~[?:?]
        at net.coreprotect.listener.PlayerListener.onInventoryClick(PlayerListener.java:149) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor16.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.jar:git-Spigot-f68f5a8-e70d864]
        ... 15 more`

**Comment by PyvesB** [comment]
@TAfirehawk the stack trace doesn't mention Advanced Achievements anywhere, it seems to be an issue with the CoreProtect implementation.

**Comment by PyvesB** [comment]
Merged everything back into _master_, closing this issue. Please open new ones if you spot anything unexpected. Here's what will probably be very close to release 5.9.0:

[AdvancedAchievements.jar.zip](https://github.com/PyvesB/AdvancedAchievements/files/2233737/AdvancedAchievements.jar.zip)

I also wrote up a [Wiki page](https://github.com/PyvesB/AdvancedAchievements/wiki/Migrating-to-Minecraft-1.13) explaining some of the gotchas when migrating to Minecraft 1.13, feel free to give it a read and make any necessary amendments.

Thanks to both of you @TAfirehawk and @aurel85, your input was well appreciated and helped a lot during the long dev hours spent on adding Minecraft 1.13 support! Hopefully the users will enjoy the new version! 😄
