### ISSUE TITLE
NoSuchMethodError: org.bukkit.entity.Player.isGliding()

### ISSUE THREAD

**Issue by Fortvy** [PyvesB/AdvancedAchievements#37]
**This gets spammed in console every 5 seconds. Please solve the Problem. I'm using Spigot 1.9 with the default config and language file.**

[22:21:20 WARN]: [AdvancedAchievements] Task #43622 for AdvancedAchievements v2.5.3 generated an exception
java.lang.NoSuchMethodError: org.bukkit.entity.Player.isGliding()Z
at com.hm.achievement.runnable.AchieveDistanceRunnable.refreshDistance(AchieveDistanceRunnable.java:286) ~[?:?]
at com.hm.achievement.runnable.AchieveDistanceRunnable.run(AchieveDistanceRunnable.java:159) ~[?:?]
at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-f32adba-bf43ca6]
at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-f32adba-bf43ca6]
at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:729) [spigot.jar:git-Spigot-f32adba-bf43ca6]
at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-f32adba-bf43ca6]
at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot.jar:git-Spigot-f32adba-bf43ca6]
at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot.jar:git-Spigot-f32adba-bf43ca6]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]

**Comment by PyvesB** [comment]
Hello,

Could you please rebuild Spigot with the latest fixes from the team (either version 1.9.2 or 1.9.4)?

**Comment by Fortvy** [comment]
Isn't there a way to keep my current Spigot version? Maybe there is a version of AdvancedAchievements available that works with 1.9?

**Comment by PyvesB** [comment]
All versions of Advanced Achievements starting from 2.4 are fully compatible with Spigot 1.9. If you want to absolutely keep your version, deactivate all the Distance achievements. But I strongly recommend to recompile Spigot, early releases are heavily bugged (for instance broken fireworks, memory leaks, etc.) and are missing many essential API methods such as this one related to the gliding feature introduced by Mojang in Minecraft 1.9. ;-)
