### ISSUE TITLE
API classes not shaded in AACH v5.10.0

### ISSUE THREAD

**Issue by Rsl1122** [PyvesB/AdvancedAchievements#439]
As you can see in the image, AdvancedAchievementsAPIFetcher.class is not included in the jar that is currently in distribution.

![issue](http://puu.sh/BGbJD/67f8900d1e.png)

Leading to exception:
```
java.lang.NoClassDefFoundError: com/hm/achievement/api/AdvancedAchievementsAPIFetcher
   com.djrapitops.pluginbridge.plan.advancedachievements.AdvancedAchievementsHook.hook(AdvancedAchievementsHook.java:34)
   com.djrapitops.pluginbridge.plan.Bridge.hookInto(Bridge.java:52)
   com.djrapitops.pluginbridge.plan.Bridge.hook(Bridge.java:46)
   com.djrapitops.plan.data.plugin.HookHandler.enable(HookHandler.java:41)
   com.djrapitops.plan.system.PlanSystem.enableSystems(PlanSystem.java:110)
   com.djrapitops.plan.system.PlanSystem.enable(PlanSystem.java:91)
   com.djrapitops.plan.system.BukkitSystem.enable(BukkitSystem.java:65)
   com.djrapitops.plan.Plan.onEnable(Plan.java:69)
   com.djrapitops.plugin.PluginCommon.reload(PluginCommon.java:19)
   com.djrapitops.plugin.BukkitPlugin.reloadPlugin(BukkitPlugin.java:83)
   com.djrapitops.plan.command.commands.ReloadCommand$1.run(ReloadCommand.java:43)
   com.djrapitops.plugin.task.RunnableFactory$1.run(RunnableFactory.java:39)
   org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:76)
   org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
   java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
   java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
   java.lang.Thread.run(Unknown Source)
```

~~Possibly introduced in commit 313f6982f3964c16b7b980f6f14d52a3866e2606~~

**Comment by PyvesB** [comment]
Thank you for reporting this @Rsl1122! I'm pretty clueless about why this would have happened at this point, I've possibly got a dirty Maven cache on my side. Does the same issue occur when your recompile Advanced Achievements from source on your own machine?

**Comment by Rsl1122** [comment]
I remember now that this exception was occurring while I was working on the inspect feature. - I brushed it off as a Plan dev version issue

**Comment by PyvesB** [comment]
Thinking about this some more, I've got an idea of what might be happening. I've enabled _jar_ minimisation in the Maven Shade plugin. This removes all unreferenced classes pulled in by dependencies external to the project you're currently building. When the _advanced-achievements-plugin_ module is packaged, Maven Shade may be removing the _AdvancedAchievementsAPIFetcher_ class coming from the _advanced-achievements-api_ module as it's not referenced anywhere. This is tricky behaviour.

**Comment by Rsl1122** [comment]
That's probably it

**Comment by PyvesB** [comment]
```
[INFO] --- maven-shade-plugin:3.2.0:shade (default) @ advanced-achievements-plugin ---
[INFO] Including com.hm.achievement:advanced-achievements-api:jar:1.1.0 in the shaded jar.
[INFO] Including javax.inject:javax.inject:jar:1 in the shaded jar.
[INFO] Including com.google.dagger:dagger:jar:2.17 in the shaded jar.
[INFO] Including org.apache.commons:commons-lang3:jar:3.8 in the shaded jar.
[INFO] Including org.apache.commons:commons-text:jar:1.4 in the shaded jar.
[INFO] Including com.hm.mcshared:MCShared:jar:1.1.3 in the shaded jar.
[INFO] Minimizing jar com.hm.achievement:advanced-achievements-plugin:jar:5.10.1
[INFO] com.hm.achievement.api.AdvancedAchievementsAPIFetcher not removed because it was specifically included
[INFO] Minimized 710 -> 399 (56%)
```

Hurray! :tada:
