### ISSUE TITLE
Missing Essentials

### ISSUE THREAD

**Issue by t0rched** [PyvesB/AdvancedAchievements#264]
I am missing Essentials when I follow steps to compile for 1.7.10...

```
[ERROR] /test/AdvancedAchievements/src/main/java/com/hm/achievement/runnable/AchievePlayTimeRunnable.java:[6,31] package com.earth2me.essentials does not exist
[ERROR] /test/AdvancedAchievements/src/main/java/com/hm/achievement/runnable/AchievePlayTimeRunnable.java:[7,31] package com.earth2me.essentials does not exist
[ERROR] /test/AdvancedAchievements/src/main/java/com/hm/achievement/runnable/AchievePlayTimeRunnable.java:[20,17] cannot find symbol
  symbol:   class Essentials
  location: class com.hm.achievement.runnable.AchievePlayTimeRunnable
```

**Comment by PyvesB** [comment]
Hello t0rched,

It's always been troublesome to keep the plugin compatible with 1.7 versions. To be totally honest, I'll probably have to drop support at some point, as I'm struggling to guarantee that support alone. 

Try adding the following to the repositories in your `pom.xml`:
```
<repository>
    <id>ess-repo</id>
    <url>http://repo.ess3.net/content/groups/essentials/</url>
</repository>
```
And try adding the following to the dependencies in your `pom.xml`:
```
<dependency>
    <groupId>net.ess3</groupId>
    <artifactId>Essentials</artifactId>
    <version>2.14-SNAPSHOT</version>
</dependency>
```

Hope this helps! :wink:

Cheers,

Pyves

**Comment by t0rched** [comment]
Closer, but still fails. I wish I knew more about Java to get it going. I did find and am using the 2.3.3 version from Bukkit without any issues. I would have just preferred to compile the new version for obvious advantages. Here is the latest build log:

`[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building AdvancedAchievements 5.3
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for net.ess3:Essentials:jar:2.14-20140906.162642-94 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ AdvancedAchievements ---
[INFO] Deleting /test/AdvancedAchievements/target
[INFO]
[INFO] --- maven-resources-plugin:2.3:resources (default-resources) @ AdvancedAchievements ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.6.0:compile (default-compile) @ AdvancedAchievements ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 77 source files to /test/AdvancedAchievements/target/classes
[INFO] /test/AdvancedAchievements/src/main/java/com/hm/achievement/listener/AchievePickupListener.java: Some input files use or override a deprecated API.
[INFO] /test/AdvancedAchievements/src/main/java/com/hm/achievement/listener/AchievePickupListener.java: Recompile with -Xlint:deprecation for details.
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /test/AdvancedAchievements/src/main/java/com/hm/achievement/utils/FileUpdater.java:[43,31] no suitable method found for set(java.lang.String,java.util.List<java.lang.String>,java.lang.String,java.lang.String,java.lang.String)
    method org.bukkit.configuration.MemorySection.set(java.lang.String,java.lang.Object) is not applicable
      (actual and formal argument lists differ in length)
    method com.hm.mcshared.file.CommentedYamlConfiguration.set(java.lang.String,java.lang.Object,java.lang.String) is not applicable
      (actual and formal argument lists differ in length)
    method com.hm.mcshared.file.CommentedYamlConfiguration.set(java.lang.String,java.lang.Object,java.lang.String[]) is not applicable
      (actual and formal argument lists differ in length)
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 17.750s
[INFO] Finished at: Thu Nov 30 03:59:06 EST 2017
[INFO] Final Memory: 17M/269M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.0:compile (default-compile) on project AdvancedAchievements: Compilation failure
[ERROR] /test/AdvancedAchievements/src/main/java/com/hm/achievement/utils/FileUpdater.java:[43,31] no suitable method found for set(java.lang.String,java.util.List<java.lang.String>,java.lang.String,java.lang.String,java.lang.String)
[ERROR] method org.bukkit.configuration.MemorySection.set(java.lang.String,java.lang.Object) is not applicable
[ERROR] (actual and formal argument lists differ in length)
[ERROR] method com.hm.mcshared.file.CommentedYamlConfiguration.set(java.lang.String,java.lang.Object,java.lang.String) is not applicable
[ERROR] (actual and formal argument lists differ in length)
[ERROR] method com.hm.mcshared.file.CommentedYamlConfiguration.set(java.lang.String,java.lang.Object,java.lang.String[]) is not applicable
[ERROR] (actual and formal argument lists differ in length)
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
`

**Comment by t0rched** [comment]
I can get it to build by using this after a few failed attempts to fix the type... Not sure how this will affect things, but it worked complete the build at least. Progress!

![image](https://user-images.githubusercontent.com/20378331/33423438-6b70ca94-d57e-11e7-89dc-fe2c3e518ae8.png)

**Comment by t0rched** [comment]
Alas, still fails as it would without any 1.7.10 changes and cloned straight from master:

> [03:33:01] [Server thread/ERROR]: Could not load 'plugins\AdvancedAchievements-5.3.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: guava10/com/google/common/collect/MultimapBuilder
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:149) ~[JavaPluginLoader.class:1.7.10-1614.58]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:334) ~[SimplePluginManager.class:1.7.10-1614.58]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:256) [SimplePluginManager.class:1.7.10-1614.58]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.java:343) [CraftServer.class:1.7.10-1614.58]
	at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:462) [ayq.class:?]
	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:138) [ayq.class:?]
	at net.minecraft.world.World.<init>(World.java:374) [ahb.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:162) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:375) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: java.lang.NoClassDefFoundError: guava10/com/google/common/collect/MultimapBuilder
	at com.hm.achievement.db.DatabaseCacheManager.<init>(DatabaseCacheManager.java:42) ~[?:?]
	at com.hm.achievement.AdvancedAchievements.<init>(AdvancedAchievements.java:202) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_151]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_151]
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_151]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:201) ~[PluginClassLoader.class:1.7.10-1614.58]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[JavaPluginLoader.class:1.7.10-1614.58]
	... 11 more
[03:33:02] [Server thread/INFO]: [WorldEdit] Loading WorldEdit v6.1.3;7a097ca

**Comment by PyvesB** [comment]
Yes, version 1.7.10 ships an antique version of Guava (over 6 years old, version 10 released back in September 2011), which is required by Advanced Achievements for its `Multimap` data structures. You therefore need to shade Guava into Advanced Achievements, so that the plugin uses its own copy of Guava and not the one pulled in by Spigot. 😉

**Comment by PyvesB** [comment]
@t0rched : I've put quite a bit of effort trying to get the plugin working with Minecraft 1.7 again. Could you please give this versions a try and see whether it works for you?

[AdvancedAchievements.zip](https://github.com/PyvesB/AdvancedAchievements/files/1533207/AdvancedAchievements.zip)

**Comment by t0rched** [comment]
@PyvesB absolutely. Will test this evening and advise, thank you for the work... will advise!

**Comment by t0rched** [comment]
Works great! I had been using 5.3 without any issues. I just wanted to try to compile from source for a few custom changes for our server. This version works great. Were you able to resolve the issues building from source?

**Comment by t0rched** [comment]
![image](https://user-images.githubusercontent.com/20378331/33643393-66dba686-da04-11e7-9821-f5b074752d04.png)

**Comment by PyvesB** [comment]
Yes, the issues building from source should be solved. The non trivial bit was to pull in a recent version of Guava properly. In addition to shading Guava into Advanced Achievements, I had to relocate all Guava's packages as they are sealed in CraftBukkit (or at least in the old Minecraft 1.7 jar I managed to find on my machine). 

I have also committed to `master` to automatically handle the `BARRIER` replacement and have updated the [Wiki](https://github.com/PyvesB/AdvancedAchievements/wiki/Installation#compiling-the-plugin-for-minecraft-1791710) instructions as well as the "special" version of [pom.xml](https://gist.github.com/PyvesB/994b1c5944677d6a9be27647bec01e95) which includes the aforementioned shading.

You should now hopefully be able to fork the repository again and start making custom changes for your server. Please let me know if you encounter any new issues! 😉
